# development docker compose file
mysql:
  image: mysql:5.7.15
  ports:
    - "3306:3306"
  volumes:
    - ./project/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: raven
    MYSQL_PASSWORD: raven
    MYSQL_DATABASE: raven
